document.addEventListener("DOMContentLoaded",async()=>{let e=extrairRefIdDoNome(skuJson?.name),t=skuJson?.skus?.[0]?.sku;if(!e||!t){console.warn("RefId ou SKU ID ausente.");return}let[i,a]=await Promise.all([buscarImagensDoSku(t),buscarVideosDoSku(e)]);renderGaleria([...i,...a]);let o=document.getElementById("modalZoom"),l=document.getElementById("zoomedImage");o.addEventListener("click",e=>{l.contains(e.target)||(o.style.display="none")})});const urlApi=(window.location.href.includes("hml")||window.location.href.includes("dev"),"https://api.autoglass.com.br");function extrairRefIdDoNome(e){if(!e)return null;let t=e.split("-").pop().trim();return/^\d+$/.test(t)?t:null}async function buscarImagensDoSku(e){let t=`${urlApi}/integracao-b2c/api/web-app/sincronismo/sku/imagens/${e}`;try{let i=await (await fetch(t)).json();return Array.isArray(i)?i.map(e=>e.Url??(e.FileLocation?`https://autoglass.vteximg.com.br/${e.FileLocation.replace(/^.*?arquivos/,"arquivos")}`:null)).filter(Boolean):[]}catch(a){return console.error("Erro ao buscar imagens:",a),[]}}async function buscarVideosDoSku(e){let t=`${urlApi}/integracao-b2c/api/web-app/sincronismo/sku/${e}`;try{let i=await (await fetch(t)).json();return i.videoList||i.Videos||[]}catch(a){return console.error("Erro ao buscar v\xeddeos:",a),[]}}function otimizarUrlVtex(e,t,i){return e.replace(/ids\/(\d+)(-\d+-\d+)?\//,`ids/$1-${t}-${i}/`)}function renderGaleria(e){let t=document.getElementById("thumbsContainer"),i=document.getElementById("mainMediaContainer");t&&i&&(t.innerHTML=i.innerHTML="",e.forEach((e,i)=>{let a=/youtube|\.mp4$|\.webm$/i.test(e),o=a?e:otimizarUrlVtex(e,60,60),l=document.createElement("li");l.className="thumb-item",l.innerHTML=a?`<div class="thumb-video"><video src="${o}" muted playsinline preload="metadata"></video></div>`:`<img src="${o}" alt="Miniatura ${i+1}" loading="lazy" width="60" height="60" >`;let n=window.matchMedia("(min-width: 768px)").matches?"mouseenter":"click";l.addEventListener(n,()=>{document.querySelectorAll(".thumb-item").forEach(e=>e.classList.remove("active")),l.classList.add("active"),exibirMidia(a?e:otimizarUrlVtex(e,400,400))}),t.appendChild(l),0===i&&(l.classList.add("active"),exibirMidia(a?e:otimizarUrlVtex(e,400,400)))}))}function exibirMidia(e){let t=document.getElementById("mainMediaContainer"),i=/youtube|\.mp4$|\.webm$/i.test(e),a=window.matchMedia("(min-width: 1024px)").matches;if(i){t.innerHTML=e.includes("youtube")?`<iframe src="${e.replace("watch?v=","embed/")}" frameborder="0" allowfullscreen width="400" height="400" ></iframe>`:`<video src="${e}" controls autoplay></video>`;return}if(a){t.innerHTML=`<div class="zoom-wrapper" data-zoom-image="${e}" style="background-image:url('${e}')">
      <div id="backgroundWhite">
        <img
          id="logo-imagem-produto"
          src="https://autoglass-cdn.github.io/arquivos/img/logo-autoglass.png"
          alt="Logo Autoglass na imagem do produto"
        />
      </div>
    </div>`;let o=t.querySelector(".zoom-wrapper");inicializarZoom(o),o.addEventListener("click",()=>{let t=document.getElementById("modalZoom"),i=document.getElementById("zoomedImage"),a=e.replace(/(\d+)-400-400/,"$1");i.src=a,t.style.display="block",inicializarZoomModal(i)})}else{t.innerHTML=`
      <img
        id="mobileZoomTrigger"
        src="${e}"
        alt="Imagem Principal"
        width="350" height="350"
        style="max-width:100%; height:auto; aspect-ratio:1/1;"
        decoding="async" fetchpriority="high"
      />
      <div id="backgroundWhite">
        <img
          id="logo-imagem-produto"
          src="https://autoglass-cdn.github.io/arquivos/img/logo-autoglass.png"
          alt="Logo Autoglass na imagem do produto"
        />
      </div>
    `;let l=document.getElementById("mobileZoomTrigger");if(l){let n=document.getElementById("logo-imagem-produto"),r=document.getElementById("backgroundWhite");n.style.display="block",r.style.display="flex",l.addEventListener("click",()=>{let t=document.getElementById("modalZoom"),i=document.getElementById("zoomedImage");window.innerWidth<500&&(i.setAttribute("width","350"),i.setAttribute("height","350"),i.style.maxWidth="100%",i.style.height="auto",i.style.aspectRatio="1 / 1"),i.src=e,t.style.display="block",inicializarZoomModal(i)})}}}function inicializarZoom(e){let t=window.matchMedia("(min-width: 1024px)").matches,i=document.getElementById("logo-imagem-produto"),a=document.getElementById("backgroundWhite");i.style.display="block",a.style.display="flex",e&&t&&(e.style.backgroundSize="100%",e.style.backgroundPosition="center",e.addEventListener("mouseenter",()=>{e.style.backgroundSize="150%",i.style.display="none",a.style.display="none"}),e.addEventListener("mousemove",t=>{let o=e.getBoundingClientRect(),l=(t.clientX-o.left)/o.width*100,n=(t.clientY-o.top)/o.height*100;e.style.backgroundPosition=`${l}% ${n}%`,i.style.display="none",a.style.display="none"}),e.addEventListener("mouseleave",()=>{e.style.backgroundSize="100%",e.style.backgroundPosition="center",i.style.display="block",a.style.display="flex"}),e.addEventListener("click",()=>{let t=document.getElementById("modalZoom");document.getElementById("zoomedImage").src=e.dataset.zoomImage,t.style.display="block"}))}function inicializarZoomModal(e){let t=!1,i=e.closest(".zoom-inner"),a=document.getElementById("logo-imagem-produto-modal"),o=document.getElementById("backgroundWhiteModal");e.addEventListener("mouseenter",()=>{i.style.transform="scale(1.5)",t=!0,a.style.display="none",o.style.display="none"}),e.addEventListener("mousemove",l=>{if(!t)return;let n=e.getBoundingClientRect(),r=(l.clientX-n.left)/n.width*100,s=(l.clientY-n.top)/n.height*100;i.style.transformOrigin=`${r}% ${s}%`,a.style.display="none",o.style.display="none"}),e.addEventListener("mouseleave",()=>{i.style.transform="scale(1)",i.style.transformOrigin="center center",t=!1,a.style.display="block",o.style.display="flex"})}