!function(e){document.addEventListener("DOMContentLoaded",async()=>{var e;let t=function e(t){if(!t)return null;let i=t.split("-").pop().trim();return/^\d+$/.test(i)?i:null}(skuJson?.name),n=skuJson?.skus?.[0]?.sku;if(!t||!n){console.warn("RefId ou SKU ID ausente.");return}let[s,d]=await Promise.all([i(n),a(t)]),r,m;e=[...s,...d],r=document.getElementById("thumbsContainer"),m=document.getElementById("mainMediaContainer"),r&&m&&(r.innerHTML=m.innerHTML="",e.forEach((e,t)=>{let i=/youtube|\.mp4$|\.webm$/i.test(e),a=i?e:o(e,60,60),n=document.createElement("li");n.className="thumb-item",n.innerHTML=i?`<div class="thumb-video"><video src="${a}" muted playsinline preload="metadata"></video></div>`:`<img src="${a}" alt="Miniatura ${t+1}" loading="lazy" width="60" height="60" >`;let s=window.matchMedia("(min-width: 768px)").matches?"mouseenter":"click";n.addEventListener(s,()=>{document.querySelectorAll(".thumb-item").forEach(e=>e.classList.remove("active")),n.classList.add("active"),l(i?e:o(e,400,400))}),r.appendChild(n),0===t&&(n.classList.add("active"),l(i?e:o(e,400,400)))}));let c=document.getElementById("modalZoom"),g=document.getElementById("zoomedImage");c.addEventListener("click",e=>{g.contains(e.target)||(c.style.display="none")})});let t=(window.location.href.includes("hml")||window.location.href.includes("dev"),"https://api.autoglass.com.br");async function i(e){let i=`${t}/integracao-b2c/api/web-app/sincronismo/sku/imagens/${e}`;try{let a=await (await fetch(i)).json();return Array.isArray(a)?a.map(e=>e.Url??(e.FileLocation?`https://autoglass.vteximg.com.br/${e.FileLocation.replace(/^.*?arquivos/,"arquivos")}`:null)).filter(Boolean):[]}catch(o){return console.error("Erro ao buscar imagens:",o),[]}}async function a(e){let i=`${t}/integracao-b2c/api/web-app/sincronismo/sku/${e}`;try{let a=await (await fetch(i)).json();return a.videoList||a.Videos||[]}catch(o){return console.error("Erro ao buscar v\xeddeos:",o),[]}}function o(e,t,i){return e.replace(/ids\/(\d+)(-\d+-\d+)?\//,`ids/$1-${t}-${i}/`)}function l(e){let t=document.getElementById("mainMediaContainer"),i=/youtube|\.mp4$|\.webm$/i.test(e),a=window.matchMedia("(min-width: 1024px)").matches;if(i){t.innerHTML=e.includes("youtube")?`<iframe src="${e.replace("watch?v=","embed/")}" frameborder="0" allowfullscreen width="400" height="400" ></iframe>`:`<video src="${e}" controls autoplay></video>`;return}if(a){var o;t.innerHTML=`<div class="zoom-wrapper" data-zoom-image="${e}" style="background-image:url('${e}')">
      <div id="backgroundWhite">
        <img
          id="logo-imagem-produto"
          src="https://autoglass-cdn.github.io/arquivos/img/logo-autoglass.png"
          alt="Logo Autoglass na imagem do produto"
        />
      </div>
    </div>`;let l=t.querySelector(".zoom-wrapper"),s,d,r;o=l,s=window.matchMedia("(min-width: 1024px)").matches,d=document.getElementById("logo-imagem-produto"),r=document.getElementById("backgroundWhite"),d.style.display="block",r.style.display="flex",o&&s&&(o.style.backgroundSize="100%",o.style.backgroundPosition="center",o.addEventListener("mouseenter",()=>{o.style.backgroundSize="150%",d.style.display="none",r.style.display="none"}),o.addEventListener("mousemove",e=>{let t=o.getBoundingClientRect(),i=(e.clientX-t.left)/t.width*100,a=(e.clientY-t.top)/t.height*100;o.style.backgroundPosition=`${i}% ${a}%`,d.style.display="none",r.style.display="none"}),o.addEventListener("mouseleave",()=>{o.style.backgroundSize="100%",o.style.backgroundPosition="center",d.style.display="block",r.style.display="flex"}),o.addEventListener("click",()=>{let e=document.getElementById("modalZoom");document.getElementById("zoomedImage").src=o.dataset.zoomImage,e.style.display="block"})),l.addEventListener("click",()=>{let t=document.getElementById("modalZoom"),i=document.getElementById("zoomedImage"),a=e.replace(/(\d+)-400-400/,"$1");i.src=a,t.style.display="block",n(i)})}else{t.innerHTML=`
      <img
        id="mobileZoomTrigger"
        src="${e}"
        alt="Imagem Principal"
        width="350" height="350"
        style="max-width:100%; height:auto; aspect-ratio:1/1;"
        decoding="async" fetchpriority="high"
      />
      <div id="backgroundWhite">
        <img
          id="logo-imagem-produto"
          src="https://autoglass-cdn.github.io/arquivos/img/logo-autoglass.png"
          alt="Logo Autoglass na imagem do produto"
        />
      </div>
    `;let m=document.getElementById("mobileZoomTrigger");if(m){let c=document.getElementById("logo-imagem-produto"),g=document.getElementById("backgroundWhite");c.style.display="block",g.style.display="flex",m.addEventListener("click",()=>{let t=document.getElementById("modalZoom"),i=document.getElementById("zoomedImage");window.innerWidth<500&&(i.setAttribute("width","350"),i.setAttribute("height","350"),i.style.maxWidth="100%",i.style.height="auto",i.style.aspectRatio="1 / 1"),i.src=e,t.style.display="block",n(i)})}}}function n(e){let t=!1,i=e.closest(".zoom-inner"),a=document.getElementById("logo-imagem-produto-modal"),o=document.getElementById("backgroundWhiteModal");e.addEventListener("mouseenter",()=>{i.style.transform="scale(1.5)",t=!0,a.style.display="none",o.style.display="none"}),e.addEventListener("mousemove",l=>{if(!t)return;let n=e.getBoundingClientRect(),s=(l.clientX-n.left)/n.width*100,d=(l.clientY-n.top)/n.height*100;i.style.transformOrigin=`${s}% ${d}%`,a.style.display="none",o.style.display="none"}),e.addEventListener("mouseleave",()=>{i.style.transform="scale(1)",i.style.transformOrigin="center center",t=!1,a.style.display="block",o.style.display="flex"})}}(jQueryNew);